# ============================================
# Paths whose presence is not useful
# ============================================
exclude = [
  ".ropeproject/",
  "uv.lock",

  # project-specific

  # environments / dependency caches
  "__pypackages__",
]

# ============================================
# Paths whose hierarchy is useful but whose contents usually are not
# ============================================
tree_only = [
  "docs",
]

# ============================================
# Tag settings
# ============================================
include_file_tags = "file"
